export const CommonError = {
	VALIDATION_FAILED: "COMMON.VALIDATION_FAILED",
	INTERNAL_ERROR: "COMMON.INTERNAL_ERROR",
	FORBIDDEN: "COMMON.FORBIDDEN",
	NO_BEARER_TOKEN: "COMMON.AUTH.NO_BEARER_TOKEN",
	ACCESS_TOKEN_INVALID: "COMMON.AUTH.ACCESS_TOKEN_INVALID",
} as const;

export type CommonErrorCode = (typeof CommonError)[keyof typeof CommonError];
