export const DEFAULT_OTEL_ENDPOINT = "http://otelcol:4318";
export const DEFAULT_METRIC_INTERVAL_MS = 15_000;
export const DEFAULT_SERVICE_NAME = "service";
export const DEFAULT_ENV = "dev";

export const EnvKeys = {
	OTEL_EXPORTER_OTLP_ENDPOINT: "OTEL_EXPORTER_OTLP_ENDPOINT",
	OTEL_SERVICE_NAME: "OTEL_SERVICE_NAME",
	SERVICE_NAME: "SERVICE_NAME",
	DEPLOY_ENV: "DEPLOY_ENV",
	NODE_ENV: "NODE_ENV",
	OTEL_METRIC_EXPORT_INTERVAL_MS: "OTEL_METRIC_EXPORT_INTERVAL_MS",
	OTEL_DIAG: "OTEL_DIAG",
} as const;
